nodeLinker: pnp
yarnPath: .yarn/releases/yarn-3.6.0.cjs

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64
  libc:
    - glibc

packageExtensions:
  '@storybook/nextjs@*':
    dependencies:
      '@babel/core': '*'
      'webpack': '*'
