nodeLinker: node-modules

packageExtensions:
  "@storybook/nextjs@*":
    dependencies:
      webpack: "*"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.0.cjs
