name: Chromatic

on:
  push:

jobs:
  chromatic-publish:
    runs-on: ubuntu-22.04

    env:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Publish to Chromatic
        run: yarn chromatic
