name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Check formatting, linting, type checking and building
        run: yarn ci
